export const browserCoreExamples = [
  "simpleclaw browser status",
  "simpleclaw browser start",
  "simpleclaw browser stop",
  "simpleclaw browser tabs",
  "simpleclaw browser open https://example.com",
  "simpleclaw browser focus abcd1234",
  "simpleclaw browser close abcd1234",
  "simpleclaw browser screenshot",
  "simpleclaw browser screenshot --full-page",
  "simpleclaw browser screenshot --ref 12",
  "simpleclaw browser snapshot",
  "simpleclaw browser snapshot --format aria --limit 200",
  "simpleclaw browser snapshot --efficient",
  "simpleclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "simpleclaw browser navigate https://example.com",
  "simpleclaw browser resize 1280 720",
  "simpleclaw browser click 12 --double",
  'simpleclaw browser type 23 "hello" --submit',
  "simpleclaw browser press Enter",
  "simpleclaw browser hover 44",
  "simpleclaw browser drag 10 11",
  "simpleclaw browser select 9 OptionA OptionB",
  "simpleclaw browser upload /tmp/simpleclaw/uploads/file.pdf",
  'simpleclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "simpleclaw browser dialog --accept",
  'simpleclaw browser wait --text "Done"',
  "simpleclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "simpleclaw browser console --level error",
  "simpleclaw browser pdf",
];
